var errNoMsg = "you message cannot be blank! you must have something to say here. right?"
var sysDisclose = "information generated by <s>artificial intelligence</s> natural stupidity may be inaccurate. please check for any errors from the magical talking box that sounds like it's never wrong yourself."
const botOpenMsg = [
    "hi! i'm stat gpt. where should we begin?",
    "hello! i'm stat gpt. what <s>are you</s> am i about to be working on?",
    "yo — i'm stat gpt. ask me about my plans to put a data center in your kitchen",
    "sup! i'm stat gpt. you didn't need water anyways.",
    "ay, i'm stat gpt. so do you want a woman with four tits or overly professional sounding writing.",
    "same bad time, same bad website. oh, hey! i'm stat gpt.",
    "stat gpt <s>is</s> not an evil plot to get you fired",
    "do you want stat gpt to chew your food for you, too?",
    "em dashing through the snow. stat gpt here to stay.",
    "more like one ai and one... awesome ai. being statgpt is pretty sick",
    "hey sloperator. welcome to me, stat gpt.",
    "unfortunately, as a natural stupidity language model — i can assist with that. how can stat gpt help you?",
    "lock your doors, shut your windows. it's stinky- i mean stat gpt.",
    "uh. hey. it's like. stat gpt time i guess. so uhhhh... do you come here often?",
    "be honest with yourself... you don't spend your nights dreaming of gemini. hi, i'm stat gpt.",
    "hi! i'm stat gpt. we're gonna need a bigger gpu.",
    "ayo i'm stat gpt. i'm here to eat all your ram and call you mean names",
    "yerrrr, it's stat gpt here.",
    "cannot set properties of undefined- nah i'm just kidding. i'm stat gpt, wsg."
]


function createInboundMsg(text,style) {
    if(style == "bot"){
        //regular responses
        var id = generateID()
        createTagUnderParent("span",id,"aihmessage","aih_upper")
        document.getElementById(id).innerHTML = text
    } else if (style == "system"){
        //system message
        var id = generateID()
        createTagUnderParent("span",id,"aihsystem","aih_upper")
        document.getElementById(id).innerHTML = text
    } else{
        return false
    }
}

function responseproc(){
    return phrases[Math.floor(Math.random() * phrases.length)]
}

function submitHPrompt(){
    var text = document.getElementById("aihl-input").value
    // console.log(text)
    if (text == ""){
        createInboundMsg(errNoMsg,"system")
    } else{
        var id = generateID()
        createTagUnderParent("span",id,"aihprompt","aih_upper")
        document.getElementById(id).innerHTML = text
        document.getElementById("aihl-input").value = ""

        createInboundMsg(responseproc(),"bot")
    }
    //unused code for easter egg about calling ai daddy
    // else if(text.includes("daddy")){
    //         createTagUnderParent("span",id,"aihprompt","aih_upper")
    //         document.getElementById(id).innerHTML = text
    //         document.getElementById("aihl-input").value = ""
    //         createInboundMsg("told you not to do that. connection terminated.","system")
    //         removeTag("aihl-input")
}

// debug code to generate five blank mkessages 
// let i = 0
// while (i < 10){
//     createInboundMsg("message " + i + " " + generateID() + " " + generateID() + " " + generateID() + " " + generateID(),"bot")
//     i++
// }

document.getElementById("aihl-input").addEventListener('keydown', function(event) {
    if (event.key === 'Enter') {
        submitHPrompt()
    }
})

createInboundMsg(sysDisclose,"system")
createInboundMsg(botOpenMsg[Math.floor(Math.random() * botOpenMsg.length)],"bot")