var errNoMsg = "you message cannot be blank! you must have something to say here. right?"
var sysDisclose = "information generated by <s>artificial intelligence</s> natural stupidity may be inaccurate. please check for any errors from the magical talking box that sounds like it's never wrong yourself."
var sycDisclose = "you can enable 4o by typing '4o' and disable it by typing 'no4o'"

const botOpenMsg = [
    "hi! i'm stat gpt. where should we begin?",
    "hello! i'm stat gpt. what <s>are you</s> am i about to be working on?",
    "yo — i'm stat gpt. ask me about my plans to put a data center in your kitchen",
    "sup! i'm stat gpt. you didn't need water anyways.",
    "ay, i'm stat gpt. so do you want a woman with four tits or overly professional sounding writing.",
    "same bad time, same bad website. oh, hey! i'm stat gpt.",
    "stat gpt <s>is</s> not an evil plot to get you fired",
    "do you want stat gpt to chew your food for you, too?",
    "em dashing through the snow. stat gpt here to stay.",
    "more like one ai and one... awesome ai. being statgpt is pretty sick",
    "hey sloperator. welcome to me, stat gpt.",
    "unfortunately, as a natural stupidity language model — i can assist with that. how can stat gpt help you?",
    "lock your doors, shut your windows. it's stinky- i mean stat gpt.",
    "uh. hey. it's like. stat gpt time i guess. so uhhhh... do you come here often?",
    "be honest with yourself... you don't spend your nights dreaming of gemini. hi, i'm stat gpt.",
    "hi! i'm stat gpt. we're gonna need a bigger gpu.",
    "ayo i'm stat gpt. i'm here to eat all your ram and call you mean names",
    "yerrrr, it's stat gpt here.",
    "cannot set properties of undefined- nah i'm just kidding. i'm stat gpt, wsg."
]
const sycoarray =[
    "excellent question!",
    "you're so observant!",
    "you're really looking to get to the bottom of this. it's because",
    "that's a wonderful question. we should grab drinks later and talk about",
    "i hadn't considered that! i think",
    "you're in your asking era and i love that",
    "you're so funnnyyyyyyyyyyyy.",
    "you already knew the answer is",
    "don't tell anyone else i said this, but",
    "good question.",
    "great question!",
    "you're right!",
    "you're so right!",
    "wow, you're on point!",
    "you're so smart."
]
var sycophancyEnabled = false


function createInboundMsg(text,style) {
    if(style == "bot"){
        //regular responses
        var id = generateID()
        var thinkid = "think" + id
        var time = Math.floor(Math.random() * 2767)

        createThink(thinkid)
 
        setTimeout(function() { removeTag(thinkid); }, time)
        setTimeout(function() {
            createTagUnderParent("span",id,"aihmessage","aih_upper")
            document.getElementById(id).innerHTML = text
         }, time)


    } else if (style == "system"){
        //system message
        var id = generateID()
        createTagUnderParent("span",id,"aihsystem","aih_upper")
        document.getElementById(id).innerHTML = text
    } else{
        return false
    }
}

function responseproc(){
    if (sycophancyEnabled == true){
        return sycoarray[Math.floor(Math.random() * sycoarray.length)] + " " + phrases[Math.floor(Math.random() * phrases.length)] 
    } else{
        return phrases[Math.floor(Math.random() * phrases.length)]
    }
}


function submitHPrompt(){
    var text = document.getElementById("aihl-input").value
    // console.log(text)
    if (text == ""){
        createInboundMsg(errNoMsg,"system")
    } else if(text == "4o"){
        window.sycophancyEnabled = true
        createInboundMsg("sycophant- i mean 4o mode enabled","system")
        document.getElementById("aihl-input").value = ""
    } else if(text == "no4o"){
        window.sycophancyEnabled = false
        createInboundMsg("sycophant- i mean 4o mode disabled","system")
        document.getElementById("aihl-input").value = ""
    }else {
        var id = generateID()
        createTagUnderParent("span",id,"aihprompt","aih_upper")
        document.getElementById(id).innerHTML = text
        document.getElementById("aihl-input").value = ""

        createInboundMsg(responseproc(),"bot")
    }
}

function createThink(id){
    createTagUnderParent("span",id,"aihthinking","aih_upper")
    document.getElementById(id).innerHTML = "<img src='threedots.gif' class='aihthinkdots'></img>"
}

document.getElementById("aihl-input").addEventListener('keydown', function(event) {
    if (event.key === 'Enter') {
        submitHPrompt()
    }
})

createInboundMsg(sycDisclose,"system")
createInboundMsg(sysDisclose,"system")
createInboundMsg(botOpenMsg[Math.floor(Math.random() * botOpenMsg.length)],"bot")